// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxg1AIHR0DrtgbVXCkbU8qlEuWoRb3ogM',
    appId: '1:773908963965:web:f72d9082c02186486b0714',
    messagingSenderId: '773908963965',
    projectId: 'project-firebase-434ac',
    authDomain: 'project-firebase-434ac.firebaseapp.com',
    storageBucket: 'project-firebase-434ac.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDQ_KDpj4aZISDZU_lV_g1d21uq2ZWflc',
    appId: '1:773908963965:android:cdd1967c4ac51b446b0714',
    messagingSenderId: '773908963965',
    projectId: 'project-firebase-434ac',
    storageBucket: 'project-firebase-434ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP4oRhGu2d7K7rVo6uKB1LQqF8M1w_DCQ',
    appId: '1:773908963965:ios:8c57f3246aec58eb6b0714',
    messagingSenderId: '773908963965',
    projectId: 'project-firebase-434ac',
    storageBucket: 'project-firebase-434ac.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP4oRhGu2d7K7rVo6uKB1LQqF8M1w_DCQ',
    appId: '1:773908963965:ios:8c57f3246aec58eb6b0714',
    messagingSenderId: '773908963965',
    projectId: 'project-firebase-434ac',
    storageBucket: 'project-firebase-434ac.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxg1AIHR0DrtgbVXCkbU8qlEuWoRb3ogM',
    appId: '1:773908963965:web:a6842aab4a2c94da6b0714',
    messagingSenderId: '773908963965',
    projectId: 'project-firebase-434ac',
    authDomain: 'project-firebase-434ac.firebaseapp.com',
    storageBucket: 'project-firebase-434ac.firebasestorage.app',
  );
}
